load '../rakelib/shared.rake'

gem_tasks(:yaks)


task :mutant_chunked do
  [
    Yaks::Attributes,
    Yaks::Attributes::InstanceMethods,
    Yaks::CollectionMapper,
    Yaks::CollectionResource,
    Yaks::Config,
    Yaks::Config::DSL,
    Yaks::Configurable,
    Yaks::Configurable::ClassMethods,
    Yaks::StatefulBuilder,
    Yaks::DefaultPolicy,
    Yaks::FP,
    Yaks::FP::Callable,
    Yaks::Format,
    Yaks::Format::CollectionJson,
    Yaks::Format::Hal,
    Yaks::Format::Halo,
    Yaks::Format::JsonAPI,
    Yaks::Mapper::AssociationMapper,
    Yaks::Mapper::Attribute,
    Yaks::Mapper::Config,
    Yaks::Mapper::HasOne,
    Yaks::Primitivize,
    Yaks::Resource,
    Yaks::Resource::Link,
    Yaks::Util,
    Yaks::Serializer,
    Yaks::Runner,
    Yaks::Mapper::Link,
    Yaks::Mapper::HasMany,
    Yaks::Mapper::ClassMethods,
    Yaks::Mapper::Association,
    Yaks::Mapper,
    Yaks::Format::HTML,
    Yaks::Mapper::Form,
    Yaks::Mapper::Form::Field,
#   Yaks::Resource::Form, #no subjects to mutate
    Yaks::NullResource,
  ].each do |space|
    puts space
    ENV['PATTERN'] = "#{space}"
    Rake::Task["mutant"].execute
  end
end
